# Generated by Django 5.1.3 on 2024-11-28 15:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('K', 'Entrega'), ('P', 'Presupuesto')], max_length=1)),
                ('numero', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('En espera', 'En espera'), ('Llamando', 'Llamando'), ('Atendiendo', 'Atendiendo'), ('No respondió', 'No respondió'), ('Finalizado', 'Finalizado')], default='En espera', max_length=20)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado_en'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'numero'), name='unique_turno')],
            },
        ),
    ]
