# Generated by Django 5.1.3 on 2024-12-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='hora_fin_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='hora_inicio_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
